on:
  push:
    branches:
      - main

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          cd web
          docker build --tag ghcr.io/$GITHUB_ACTOR/gawk-rubber-duck:latest \
          --tag ghcr.io/$GITHUB_ACTOR/gawk-rubber-duck:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/gawk-rubber-duck:latest
          docker push ghcr.io/$GITHUB_ACTOR/gawk-rubber-duck:$(echo $GITHUB_SHA | head -c7)
